### PR TITLE
Close  #14 mexican_wave in js

### LINKED ISSUE #14: 58f5c63f1e26ecda7e000029 | Mexican Wave | JavaScript

### PR DESCRIPTION
**Pull request by yafiwebdev**

### CODE REVIEW

**Comment by yafiwebdev** [comment]
Hey @GoodGuyGregory 
Solved both open issues, please approve if everything's alright.
Will try to commit two more 6 kyu katas by tomorrow or the day after.
I might also start solving issues in Python as well.

**Comment by yafiwebdev** [comment]
I'd appreciate it if you would approve it quickly, as this is my last PR to complete all 4 of Hacktoberfest's PRs.

Thank you very much!

**Comment by GoodGuyGregory** [comment]
@yafiwebdev sorry about the delay! all closed up! I hope this assisted you this year!

**Comment by GoodGuyGregory** [comment]
see you next year 🎃

**Comment by yafiwebdev** [comment]
Thanks, man!
Turns out I can create PRs on my own repos, but I'm glad I contributed to yours, and will add more even after Hacktoberfest.
If you're really interested in algorithms, you should consider taking on Project Euler problems, it might be more exciting, albeit harder, than doing katas.
You're welcome to add to my repo in the Java folder for example.
yafiwebdev/ProjectEuler100

**Pull request merged**
